name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies (Server)
        run: cd Server && npm install

      - name: Generate Prisma Client
        run: cd Server && npx prisma generate

      - name: Build Server
        run: cd Server && npm run build

      - name: Install Dependencies (Web)
        run: cd web && npm install

      - name: Build Web
        run: cd web && npm run build
